#eureka:
#  client:
#    service-url:
#      defaultZone: http://server1:11111/eureka,http://server2:11112/eureka
spring:
  application:
    name: application.gateway
  cloud:
    config:
      profile: test
      label: master
      uri: http://10.122.3.207:8888/
      name: gateway
#server:
#  port: 5555
#定制actuator的info信息 @XX@ XX来自于pom.xml
info:
  app:
    name: @project.name@
    description: @project.description@
    version: @project.version@
#zuul:
#  filter:
#      root: ./dynamic-zuul-fileter
#      interval: 5
#  ignored-patterns: /**/hello1/**
#  add-host-header: true
#  retryable: true
  #重定向引起的url为真正实例的url
  #敏感信息传递 cookie、set-cookie、Authorization
#  sensitive-headers:
#  routes:
#    hello-provider:
#  prefix: /gateway
#  strip-prefix: false
#zuul:
#  routes:
#    HELLO-PROVIDER:
#      path: /hello-server/**
#      serviceId: HELLO-PROVIDER

#actuator
#修改访问路径  2.0之前默认是/   2.0默认是 /actuator  可以通过这个属性值修改
#management.endpoints.web.base-path=/monitor
#开放所有页面节点  默认只开启了health、info两个节点
#management.endpoints.web.exposure.include=*
#显示健康具体信息  默认不会显示详细信息
#management:
#  endpoint:
#    health.show-details: always